# Generated by Django 4.2.5 on 2023-09-08 14:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0002_client_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationForm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_time', models.CharField(blank=True, default='', max_length=255)),
                ('gender', models.CharField(blank=True, default='', max_length=255)),
                ('marital_status', models.CharField(blank=True, default='', max_length=255)),
                ('occupation', models.CharField(blank=True, default='', max_length=255)),
                ('department', models.CharField(blank=True, default='', max_length=255)),
                ('present_address', models.CharField(blank=True, default='', max_length=255)),
                ('home_district', models.CharField(blank=True, default='', max_length=255)),
                ('mobile_number', models.CharField(blank=True, default='', max_length=255)),
                ('your_problem', models.TextField(blank=True, default='', max_length=1024)),
                ('referred_by', models.CharField(blank=True, default='', max_length=255)),
                ('type_of_service', models.CharField(blank=True, default='', max_length=255)),
                ('official_comment', models.TextField(blank=True, default='', max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
