# Generated by Django 4.2.6 on 2023-10-21 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationForm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationform',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
