# Generated by Django 4.2.6 on 2023-10-21 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counselor', '0001_initial'),
        ('registrationForm', '0002_registrationform_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationform',
            name='counselor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='counselor.counselor'),
        ),
    ]
