# Generated by Django 4.2.6 on 2023-10-21 04:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registrationForm', '0003_registrationform_counselor'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationform',
            name='session_location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='registrationform',
            name='session_status',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='registrationform',
            name='session_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrationform',
            name='suggested_questionnaire',
            field=models.TextField(blank=True, default=''),
        ),
    ]
