# Generated by Django 4.2.6 on 2023-10-30 01:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registrationForm', '0004_registrationform_session_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationform',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='registrationform',
            name='session_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
