# Generated by Django 4.2.5 on 2023-09-08 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminCounselor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admincounselor',
            name='criteria',
            field=models.TextField(blank=True, default=''),
        ),
    ]
