# Generated by Django 4.2.5 on 2023-09-08 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminCounselor', '0002_admincounselor_criteria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admincounselor',
            name='criteria',
        ),
    ]
