# Generated by Django 4.2.5 on 2023-09-08 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_alter_questionnaire_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filledquestionnaire',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='evaluation_range',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='options',
            field=models.TextField(blank=True, default=''),
        ),
    ]
